### ISSUE TITLE
Allow to return void in addSyncMap

### ISSUE THREAD

**Issue by g12i** [logux/server#130]
It may be necessary to skip actions under certain circumstances. 

E.g. when creating sync map `load()` is called by the time it may be actually created in database.

```ts
addSyncMap({
  async load(ctx, id, since, action) {
    if (action.creating) {
      return;
    }

    // ....

    return {
      id: "foo",
      projectId: NoConflictResolution("bar"),
    };
  },
});

```

**Comment by ai** [comment]
We will add `skip` optional callback to `addSyncMap()`. Is it that API which will solve your problem?

Also, should we just fix `load` on creation? Will it bother all users or do we have a specific use case?

**Comment by ai** [comment]
> Perhaps maybe just an union then?

It will be different from `access` signature. It is better to keep consistency. Especially for rare hack API.

**Comment by ai** [comment]
I did a little different way by allowing `return false` from `load()` callback. ea597e7

Is it OK?

**Comment by ai** [comment]
I also disabled `load` for `action.creating` out of the box b6019b0

Please check `next` branch on your system and I will release it.
