### ISSUE TITLE
Unstable acceptance test 'shows uncatch rejects'

### ISSUE THREAD

**Issue by artmnv** [logux/server#26]
Acceptance test 'shows uncatch rejects' in server.test.js has this snapshot:
```
 ERROR  Test Error at 1970-01-01 00:00:00
        fake stacktrace

Error event: Test Error
 INFO   Shutting down Logux server at 1970-01-01 00:00:00
```

But sometimes two last lines come in another order. That's because of race condition. We need to stabilise this test. Maybe with some timeout?

**Comment by artmnv** [comment]
Example of failed job: https://travis-ci.org/logux/logux-server/jobs/213092586

**Comment by ai** [comment]
Yeap, seems like tests are not 100% stable. Do you want to send PR?

**Comment by artmnv** [comment]
@ai If I'll figure out how to fix this. Any hits? Anyway I'll think for myself.

**Comment by ai** [comment]
Have no idea right now. I can help you here after React London (March 29).
