### ISSUE TITLE
Hello from Antares

### ISSUE THREAD

**Issue by deanius** [logux/server#33]
A friend of mine pointed me to your presentation at ReactConf. Your library and mine really try to solve similar problems.. https://github.com/deanius/antares

Some differences:

* Antares actions sync by default, staying local with `localOnly: true`
* I hide the `dispatch` inside `announce` to make this sync-by-default behavior clear
* I bundle the Redux-Observable library to include Epics functionality via RxJS, and showcase with a WhatsApp-style chat app
* You are more precise about timing and log sync, and I will likely borrow some of your ideas!

Let me know how you think I could help Logux - at the very least I will mention it as an alternative, much the way you mention Swarm.js. I think we have a lot of similar inspirations (yet, I'm jealous that you got to rap with Dan Abramov about it over drinks in St Petersberg - my visit there was fun but lacked that conversation ;) )

Dean

**Comment by ai** [comment]
Hi. Awesome project!

After June 9 I will be back in good Internet and will look. I think there are a few good think from Logux, that can be useful for you. But also I see that you did great Redux and RxJS integration, so your help could be extremely useful.

**Comment by ai** [comment]
OK, I was the very bad person and lost this issue :sweat: (too many Cuban rum :D).

Also I really jealous about how great is your Redux integration. I plan to write it only Redux integration only in July.

Your docs are great, I can only dream about them :D.

Two projects with the same idea definitely shows that:

1. Client server communication will be next big thing.
2. Maybe we need something further than Relay.

I think the main problem (you know Russians are very strict :D) of Antares is that its server is based on top of Meteor. But maybe I am wrong about current Meteor status (seems like most of the resources were moved to Apollo, but maybe they rewrite Meteor on top of Apollo in some moment).

I think the idea of uniting or powers is very obvious. I have a few questions about your client-side part:

1. How did you store actions?
2. Do you save actions if a user will close browser tab?
3. Do you same storage for multiple browser tabs of the single website?
4. Do you have some cross-tab communication?
