### ISSUE TITLE
Allow keeping reasons of action from server

### ISSUE THREAD

**Issue by hardchiu** [logux/server#46]
### Mission
Synchronize data via channel and action with flow like:
1. when client subscribed, send action in the channel method to send initial data to client
2. having actions modifying the data and sync the action via the channel in 1

### Problem
All the action send from server will got ```reasons``` filtered out before sending to client, so that client will not keep any log received from server.

This caused problem in a case that client and server simultaneously logging action in parallel.
e.g.
Client Sequence: C1, C2
Server Sequence: S1, S2
Absolute time sequence: C1 S1, S2, C2

The client got C1, C2 finished before receiving S1, S2 from server. If I understand correctly, when
* S1 reach client, the client will replaceState to state at C1 and run S1, C2
* S2 reach client, the client will replaceState to state at C1 and only run S2, C2

Since S1 has no any ```reasons``` in the client side, the log is not saved and the S1 change is missed.

### Expectation
* S2 reach client, the client will replaceState to state at S1 and run S2, C2

### Notes
_I am not sure if logux is designed to work like this, please tell if I have used it incorrectly.
(I found action send in channel method will not reach non-leader crossTab client, so maybe I am doing it wrong. Currently I patched to use Client instead of CrossTabClient)_

Allowing ```reasons``` from server enable the server to hint the client how to manage the log, otherwise the client will need to define it themselves and it may not be the desired way to use the log.

For keeping clients log sync via channel, it require some reasoning too, we need some way to suggest how the log are kept.
Currently the sync server sendAction before the action is processed, so that we don't have chance to add any ```reasons``` in the action handler before sending out.
(as a workaround, I have locally temp enabled reasoning from client, since I am not sure if it is safe to move processAction before sendAction)

Since the above mission is common, if logux-server can do some automatic reasoning for channel, maybe we can keep custom ```reasons``` filtered out. Maybe related to this: https://github.com/logux/logux-server/issues/40

### Security
It should be fine to allow ```reasons``` from server.
For allowing ```reasons``` from client, I can understand why it is filtered. If it is not filtered, client can flood the server storage.

### Temp fix
I have locally do:

1. Add ```reasons``` to ALLOWED_META both in logux-client and logux-server
2. Add ```reasons``` and ```keepLast``` in server-client.js outMap
3. Added ```outMap``` as config in logux-client/client.js
4. Pass ```outMap``` to client config for filtering ```tab*```, ```replay``` and ```waitForSync``` in logux-redux
(4 sound problematic, I wish the reasons for log sycned via channel can be specify in server)

In my application:

5. Send initial data in channel with channel name as ```keepLast```
6. Client send action to channel also with the channel name as ```reasons```
(maybe that can be generalized and do reason automatically)

**Comment by ai** [comment]
> Since S1 has no any reasons in the client side, the log is not saved and the S1 change is missed.

It is docs problem. My original idea was to use `log.on('preadd'` to add `reasons` to server-side (and any other) actions.

Here is a code from my client:

```js
log.on('preadd', (action, meta) => {
    if (action.type === 'amplifr/notices/add') {
      const id = action.notice.id
      const isHidden = firstHide[id]
      const isLastAdd = isFirstOlder(lastAdd[id], meta)
      if (!isHidden && isLastAdd) {
        lastAdd[id] = meta
        meta.reasons.push(`amplifr/notice/${ id }/add`)
        log.removeReason(`amplifr/notice/${ id }/add`, { olderThan: meta })
        log.removeReason(`amplifr/notice/${ id }/see`, { olderThan: meta })
      }
```

(Also I very like your issues/PR — you put a lot of details, thanks)
