### ISSUE TITLE
A complete example app?

### ISSUE THREAD

**Issue by nevf** [logux/server#49]
Is there a complete example app available? I am trying to update https://github.com/Mavrin/logux-example to the current version of Logux and failing. This is the only complete example I have been able to find.

With the documentation scattered amongst all the different modules it is difficult to get a complete understanding of all the Logux workings, sufficiently enough to get something working.  At least for me.

Any help greatly appreciated. 

It sure would be nice to see Logux become more widely used. If I understand its capabilities correctly it certainly has excellent potential in the offline, decentralized app world.

**Comment by ai** [comment]
Yeap. It is the biggest current problem of Logux.

My next step will be creating a docs and examples. But honestly, I am on the open source vacation right now. Plan to return next month.

If you have any question about Logux you can write it here or on andrey@sitnik.ru. Your questions will be really helpful to understand problem parts of Logux docs and API (you know, creator can't see explanation problems 😅).

**Comment by nevf** [comment]
@ai Thanks, I've sent you an email outlining my current problem. I understand only too well the problems of us creators being too close to our work.

**Comment by nevf** [comment]
@ai I found the problem with the server not seeing data from the client after watching your London video.
````
    logux.log.add( { type: 'addItem',
                     payload
                   },{
                     sync: true,     // this is the clincher - missing from Docs.
                     reasons: ['lastValue']
                   }
    )
````
There is no mention of setting the ```sync``` property in any of the client, core etc. docs.

**Comment by ai** [comment]
Yeap, I told about it only in Logux Redux. Do you want send PR to Logux Client?

**Comment by nevf** [comment]
@ai I think it would be quicker and easier for you to just update the docs. 

I will get back in touch when I finish getting everything working with suggestions for the docs. 

Am I correct that to load the clients with any initial data from the server I need to use channels as mentioned at https://github.com/logux/logux-server ?

**Comment by ai** [comment]
Yeap. Define a channel on the server, put some initial data on channel subscription, create `logux/subscribe` on the client with `sync: true`.

**Comment by stereobooster** [comment]
Trying to update example. No luck so far https://github.com/Mavrin/logux-example/pull/1/files

**Comment by ai** [comment]
Don’t worry. I will create a example app, when I will start docs.

**Comment by ai** [comment]
Moved to https://github.com/logux/logux/issues/5
