### ISSUE TITLE
Use async/await

### ISSUE THREAD

**Issue by ai** [logux/server#55]
Logux Server 0.3 requires Node.js >= 10, so we are safe to use `async`/`await` instead of `Promise`

**Comment by ai** [comment]
Part of the works was done in https://github.com/logux/server/pull/58

@chafilin can you show me links to the code, where you have problems in replacing Promise?

**Comment by ai** [comment]
@chafilin don’t forget about tests. They are the main users of `.then`.

**Comment by chafilin** [comment]
> Part of the works was done in #58
> 
> @chafilin can you show me links to the code, where you have problems in replacing Promise?

This kind of Promises: https://github.com/logux/server/blob/b47dccd9e0093a4a8dc65fa06195046c2e2d1462/bind-backend-proxy.js#L106
https://github.com/logux/server/blob/b47dccd9e0093a4a8dc65fa06195046c2e2d1462/bind-backend-proxy.js#L42

**Comment by ai** [comment]
Yeap. Let’s keep Promise in those 2 examples.

I am waiting for PR to replace `then` in tests.

**Comment by ai** [comment]
The current list of `.then` in project

```
➜ rg "\.then"
server-client.js
275:      .then(result => {

base-server.js
388:        .then(() => Promise.all(before))
389:        .then(keys => new Promise((resolve, reject) => {
405:    promise = promise.then(() => {
410:      promise.then(() => {
420:    return promise.then(() => {
424:    }).then(() => {
921:        }).then(access => {
960:            }).then(() => emitSubscribed())
964:        }).then(access => {

force-promise.js
8:  if (typeof result !== 'object' || typeof result.then !== 'function') {

test/force-promise.test.js
4:  return forcePromise(() => Promise.resolve('result')).then(result => {
11:  return forcePromise(() => Promise.resolve().then(() => {
19:  return forcePromise(() => 'result').then(result => {

test/base-server.test.js
580:  app.destroy().then(() => {

test/stress/client.js
70:  delay(Math.random() * 10000).then(() => {

test/stress/backend.js
46:    let processing = delay(500).then(() => {
50:      processing = processing.then(() => {
52:      }).then(() => {
58:      }).then(() => {
62:      processing = processing.then(() => {
64:      }).then(() => {
68:    processing.then(() => {
```

Seems like we have only a few lines to close this issue.

**Comment by ai** [comment]
https://github.com/logux/server/commit/a369b484acd10bd1697c9345eff10bc78689886c
https://github.com/logux/server/commit/b99e4bef7c23a1efee07dd0190f0437eb8f4aefc
https://github.com/logux/server/commit/72f6894eaa4de8cc96f94640ea321f07e65d8079
https://github.com/logux/server/commit/6399e06d808d25b2f364e4d65dbae7c15a4c7df5
https://github.com/logux/server/commit/66d61c49ac3809acea2979bafb2f4413a70cbb6e

**Comment by uncaught** [comment]
What is the reason for the `forcePromise` module? You can `await` promises and non-promises.

**Comment by ai** [comment]
API was created before `await`.

Good idea to remove it. Do you want to send PR?

**Comment by uncaught** [comment]
Hmm, I would, but one test fails and I don't know why.
The test `reports about errors during channel authorization` has this assertion:
`expect(test.names).toEqual(['add', 'clean', 'error', 'add', 'clean'])`
But `test.names` is now `['add', 'error', 'add', 'clean', 'clean']`.

**Comment by ai** [comment]
1. I forgot to say you send PR to `v0.6` branch instead of `master`
2. You can find reports content in `test.reports`. Comparing `test.reports before and after changes could help you with finding a difference. It is OK if the content is the same, but only the order was changed.
3. If it will become too complicated you can send failing PR, I will help with tests.
