### ISSUE TITLE
Add API to block action resending

### ISSUE THREAD

**Issue by ai** [logux/server#57]
Now Logux Server will resend all override actions. We need a API to tell not to process and re-send action.

**Comment by ai** [comment]
Nope, this issue only about optimization. If the server received `rename to A` and older `rename to B` actions, the server doesn’t need to send `rename to A` to all clients, because it was overridden by `rename to B`.

**Comment by ai** [comment]
> Does this issue about any client can say server to resend action to any node/client/user/channel?

Why does `server.type(action, { access })` not help yoou will access control?

**Comment by farwayer** [comment]
Ok, I opened new issue for discussion. I follow the logux development and it looks very interesting but this behaviour...
