### ISSUE TITLE
Add Server#autoloadModules

### ISSUE THREAD

**Issue by ai** [logux/server#84]
This method should be in `Server`, not `BaseServer`. It should:

1. Take `this.options.root` and load all `modules/*` files.
2. Each module will have `server => void` signature.

**Comment by kabbi** [comment]
I think it's worth considering next.js filesystem-based routing experience, something like
```
.
|-- actions
|   `-- users
|       |-- add.js
|       `-- rename.js
`-- channels
    `-- users
        `-- [id].js
```
Maybe not in the core API though

**Comment by ai** [comment]
This issue already fixed in `next` branch with an option to override pattern.
