### ISSUE TITLE
Add verbose mode for the server to provides additional details

### ISSUE THREAD

**Issue by egregors** [logux/server#88]
If we find a way to get detailed logs at server runtime, it will be much easier to develop some integration for Logux.

At my vision, for the start the server in the verbose mode should prints:

- [ ] All requests to and from the proxy server (host, method, headers, etc)
- [ ] All WS connections \ disconnections
- [ ] Informative error messages

**Comment by ai** [comment]
> All WS connections \ disconnections

Why `Client was connected` and `Client was disconnected` do not work for your?

> Informative error messages

What we can add to the current error messages?
