### ISSUE TITLE
Remove reporter from public API 

### ISSUE THREAD

**Issue by AleksandrSl** [logux/server#92]
As it was suggested by @ai we can keep only `logger: 'human' | 'json' | PinoLogger`

Arguments:
* Reporter API is more "low-level" than logger. 
* Both reporter and logger has some corner cases in cofiguration. 
   e.g. 
   * If we specify custom logger and custom reporter, custom logger will be ignored
   * If we specify custom logger and `human` reporter, custom logger will also win and "human" 
      reporter is ignored
* Reason for both of them to exist in public API is mostly historical (https://github.com/logux/server/pull/91#issuecomment-627336022)

**Comment by ai** [comment]
I found that we need function based reporter to tests :(

**Comment by AleksandrSl** [comment]
What a misfortune,  I almost submitted PR :)
Maybe we can at least move `json` and `human` options to logger? This could remove some inconsistencies.

**Comment by ai** [comment]
Sure
